kind: pipeline
type: docker
name: default

steps:
- name: gobuild
  image: golang:1.22.3
  commands:
  - echo go build
  - cd src
  - env GOOS=linux GOARCH=amd64 go build -o demo-app

- name: dockerPush
  image: plugins/docker
  settings: 
    repo: shengzhen4docker/go
    use_cache: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  tags:
    - latest
