kind: pipeline
type: docker
name: default

steps:
- name: gobuild
  image: golang:1.22.3
  commands:
  - echo go build
  - cd src
  - env GOOS=linux GOARCH=amd64 go build -o demo-app

- name: dockerPush
  image: docker:dind
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  commands:
    - sleep 5
    - cd src
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
    - DOCKER_BUILDKIT=1 docker build -t shengzhen4docker/go:v1.0 .
    - docker push  shengzhen4docker/go:v1.0
  
